<?php

namespace CareerBundle\Repository;

/**
 * ApplicationStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
