<?php

namespace AppBundle\Repository;

/**
 * ApplicantPatrolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicantPatrolRepository extends \Doctrine\ORM\EntityRepository
{
}
