<?php

namespace AppBundle\Repository;

/**
 * ApplicantScenariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicantScenariosRepository extends \Doctrine\ORM\EntityRepository
{
}
