<?php

namespace AppBundle\Repository;

/**
 * CommendationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommendationRepository extends \Doctrine\ORM\EntityRepository
{
}
