<?php

namespace AppBundle\Repository;

/**
 * InactivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InactivityRepository extends \Doctrine\ORM\EntityRepository
{
}
