<?php

namespace AppBundle\Repository;

/**
 * InfractionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfractionRepository extends \Doctrine\ORM\EntityRepository
{
}
